export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_SELECTED_PRODUCT = "FETCH_SELECTED_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
